src/main/java/com/sfl/task/cafe/domain/manager/CafeTable.java
package com.sfl.task.cafe.domain.manager;

import com.sfl.task.cafe.domain.inventory.Category;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.seedstack.business.domain.BaseEntity;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.util.Date;

/**
 * CafeTables
 * 			id INT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 * 			number INT NOT NULL,
 * 			waiterId INT NULL,
 * 		    status TINYINT NOT NULL DEFAULT 0,
 * 			capacity INT NOT NULL,
 * 			place VARCHAR(50) NULL
 *
 */

@Getter
@Setter
@Entity(name = "cafeTables")
@Table(name = "cafeTables")
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public final class CafeTable extends BaseEntity<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * Table number to identify
     */
    @Column(name = "number", nullable = false)
    private Integer number;

    /**
     * The capacity of Table
     */
    @Column(name = "capacity", nullable = false)
    private Integer capacity;

    /**
     * Where is the table
     */
    @Column(name = "place", nullable = false)
    private String place;

    /**
     * Waiter attached to table
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "waiterId", referencedColumnName = "id")
    private User waiter;

    /**
     * Table Status
     */
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.ORDINAL)
    private TableStatus status = TableStatus.AVAILABLE;

    @Override
    public Long getEntityId() {
        return getId();
    }

}

src/main/java/com/sfl/task/cafe/domain/manager/TableStatus.java
package com.sfl.task.cafe.domain.manager;

/**
 * Possible table status enumeration
 */
public enum TableStatus {

    /**
     * table is Available
     */
    AVAILABLE(1),

    /**
     * table is Reserved
     */
    RESERVED(2),

    /**
     * Table is not available
     */
    UNAVAILABLE(3);

    private final int numStatus;

    TableStatus(int numStatus) {
        this.numStatus = numStatus;
    }

    public String getDescription() {
        return toString();
    }

    public int getNumStatus() {
        return numStatus;
    }
}

src/main/java/com/sfl/task/cafe/domain/manager/User.java
package com.sfl.task.cafe.domain.manager;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.seedstack.business.domain.BaseEntity;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Date;
import java.util.List;

/**
 *   id INT IDENTITY(1, 1) NOT FOR REPLICATION NOT NULL,
 * 			roleId  TINYINT NOT NULL,
 * 			firstName VARCHAR(50) NULL,
 * 			lastName VARCHAR(50) NULL,
 * 			userName VARCHAR(50) NULL,
 * 			mobile VARCHAR(50) NULL,
 * 			email VARCHAR(50) NULL,
 * 			passwordHash VARCHAR(500) NOT NULL,
 * 			registeredAt DATETIME NOT NULL,
 * 			lastLogin DATETIME NULL,
 */
@Getter
@Setter
@Entity(name = "users")
@Table(name = "users")
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public final class User extends BaseEntity<Long> implements UserDetails{
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "firstName", nullable = true, length = 50)
    private String firstName;

    @Column(name = "lastName", nullable = true, length = 50)
    private String lastName;

    @Column(name = "username", nullable = true, length = 50)
    private String username;

    @Column(name = "mobile", nullable = true, length = 50)
    private String phone;

    @Column(name = "email", nullable = true, length = 50)
    private String email;

    @Column(name = "passwordHash", length = 20)
    private String password;

    @Column(name = "registeredAt", nullable = false)
    private Date registeredAt;

    @Column(name = "lastLogin")
    private Date lastLogin;
    /**
     * User Role
     */
    @Column(name = "roleId", nullable = false)
    @Enumerated(EnumType.ORDINAL)
    private UserRole role = UserRole.WAITER;

    @Override
    public Long getEntityId() {
        return getId();
    }

    /**
     * Return user roles by object SimpleGrantedAuthority.
     * {@link UserDetails} implementation.
     *
     * @return {@link Collection} -list of roles
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        final List<GrantedAuthority> roles = new ArrayList<>();
        SimpleGrantedAuthority authority = new SimpleGrantedAuthority("ROLE_" + this.role.name());
        roles.add(authority);
        return roles;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
}

src/main/java/com/sfl/task/cafe/domain/manager/UserRole.java
package com.sfl.task.cafe.domain.manager;

/**
 * Possible user roles enumeration
 */
public enum UserRole {
    /**
     * Waiter role
     */
    WAITER(1),

    /**
     * cafe manager role
     */
    MANAGER(2),

    /**
     * Product Item SUPPLIER role
     */
    SUPPLIER(3);

    private int numRole;

    UserRole(int numRole) {
        this.numRole = numRole;
    }

    public String getDescription() {
        return toString();
    }

    public int getNumRole() {
        return numRole;
    }
}

src/main/java/com/sfl/task/cafe/domain/orderprocess/Order.java
package com.sfl.task.cafe.domain.orderprocess;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.seedstack.business.domain.BaseEntity;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import javax.persistence.*;
import java.util.Collection;
import java.util.Date;
import java.util.HashSet;

/**
 * Orders
 * 			id INT IDENTITY(1,1) NOT FOR REPLICATION NOT NULL,
 * 			userId INT NOT NULL,
 * 			orderCode VARCHAR(100) NOT NULL,
 * 			cafeTableId INT NOT NULL,
 * 			status TINYINT NOT NULL,
 * 			total DECIMAL NOT NULL DEFAULT 0,
 * 			discount DECIMAL NOT NULL DEFAULT 0,
 * 			ItemDiscount DECIMAL NOT NULL DEFAULT 0,
 * 			paidTotal DECIMAL NOT NULL DEFAULT 0,
 * 			createdAt DATETIME NOT NULL,
 * 			updatedAt DATETIME NULL,
 */
@Getter
@Setter
@Entity(name = "orders")
@Table(name = "orders")
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public final class Order extends BaseEntity<Long> {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    @Column(name = "cafeTableId", nullable = false)
    private Long tableId;

    @Column(name = "userId", nullable = false)
    private Long waiterId;

    @Column(name = "orderCode", nullable = false, length = 100)
    private String orderCode;

    /**
     * The full / total price. without any discount.
     */
    @Column(name = "total", nullable = false)
    private Double total;

    /**
     * The total discount for personal discount.
     */
    @Column(name = "discount", nullable = false)
    private Double discount;

    /**
     * Ordered Items total discount.
     */
    @Column(name = "ItemDiscount", nullable = false)
    private Double ItemDiscount;

    /**
     * The paid by customer total price
     */
    @Column(name = "paidTotal", nullable = false)
    private Double paidTotal;

    @Column(name = "createdAt")
    private Date createdAt;

    @Column(name = "updatedAt")
    private Date updatedAt;

    /**
     * Table Status
     */
    @Column(name = "status", nullable = false)
    @Enumerated(EnumType.ORDINAL)
    private OrderStatus status = OrderStatus.NEW;

//    /**
//     * The list of products connected with current category
//     */
//    @OneToMany(
//            fetch = FetchType.LAZY,
//            mappedBy = "products_in_order",
//            cascade = CascadeType.ALL
//    )
//    private Collection<Transaction> products = new HashSet<>();

    @Override
    public Long getEntityId() {
        return getId();
    }

}

src/main/java/com/sfl/task/cafe/web/manager/ManagerController.java
package com.sfl.task.cafe.web.manager;

import com.sfl.task.cafe.domain.manager.User;
import com.sfl.task.cafe.domain.manager.UserRole;
import com.sfl.task.cafe.event.manager.TableAssignedToWaiterEvent;
import com.sfl.task.cafe.messaging.manager.CafeManagerChannels;
import com.sfl.task.cafe.repository.manager.CafeTableRepository;
import com.sfl.task.cafe.repository.manager.UserRepository;
import com.sfl.task.cafe.service.manager.IUserService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.messaging.support.MessageBuilder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.servlet.ModelAndView;

@Controller
@RequestMapping(path = "manager")
@ComponentScan(basePackages = {"com.sfl.task.cafe.repository", "com.sfl.task.cafe.service", "com.sfl.task.cafe.messaging.manager"})
public class ManagerController {
    private final static Logger LOGGER = LoggerFactory.getLogger(ManagerController.class);

    private final CafeTableRepository cafeTableRepository;
    private final UserRepository userRepository;
    //private final CafeManagerChannels cafeManagerChannels;
    private final IUserService userService;

    @Value("${nextProcessStepUrl}")
    private String nextProcessStepUrl;

    @Autowired
    @SuppressWarnings("SpringJavaAutowiringInspection")
    public ManagerController(final CafeTableRepository cafeTableRepository,
                             final UserRepository userRepository,
                             final IUserService userService
                             //final CafeManagerChannels cafeManagerChannels
                             ) {
        this.cafeTableRepository = cafeTableRepository;
        this.userRepository = userRepository;
        //this.cafeManagerChannels = cafeManagerChannels;
        this.userService = userService;
    }

    /**
     * Return All users "manager/user/all".
     * URL request {"/manager/user", "/user/manager/", "/manager/user/all"},
     * GET.
     *
     * @return object of class {@link ModelAndView}.
     */
    @RequestMapping(
            value = {"", "/", "/all"},
            method = RequestMethod.GET
    )
    public ModelAndView viewAllManagers() {
        final ModelAndView modelAndView = new ModelAndView();
        modelAndView.addObject("users", this.userService.getManagers());
        modelAndView.addObject("manager_role", UserRole.MANAGER);
        modelAndView.addObject("waiter_role", UserRole.WAITER);
        modelAndView.addObject("auth_user", this.userService.getAuthenticatedUser());
        modelAndView.setViewName("user/manager/all");
        return modelAndView;
    }


    @RequestMapping(
            value = {"/user/{username}"},
            method = RequestMethod.GET)

    public ModelAndView index(@PathVariable String username) {

        LOGGER.info("Received a request for a user: " + username);
        User user = userRepository.findByUsername(username);

        final ModelAndView modelAndView = new ModelAndView();
        modelAndView.addObject("user", user);
        modelAndView.addObject("manager_role", UserRole.MANAGER);
        modelAndView.addObject("waiter_role", UserRole.WAITER);
        modelAndView.addObject("auth_user", this.userService.getAuthenticatedUser());
        modelAndView.addObject("roles", UserRole.values());
        modelAndView.setViewName("user/manager/one");
        return modelAndView;
    }


    @PostMapping("/manager/waiter/{waiterId}/table/{tableId}/assign")
    public ModelAndView assignTableToWaiter(@PathVariable Long waiterId,
                                      @PathVariable Long tableId,
                                      Model model) {
        LOGGER.info("Received assignTableToWaiter waiter: " + waiterId + "table: " + tableId);

        // We are sending a TableAssignedToWaiterEvent
        TableAssignedToWaiterEvent event = new TableAssignedToWaiterEvent();
        event.setTableId(tableId);
        event.setWaiterId(waiterId);
//        cafeManagerChannels.tableAssignedToWaiterOut()
//                .send(MessageBuilder.withPayload(event).build());
        LOGGER.info("Sent " + event.toString());

        final ModelAndView modelAndView = new ModelAndView();
        modelAndView.addObject("waiterId", waiterId);
        modelAndView.addObject("manager_role", UserRole.MANAGER);
        modelAndView.addObject("waiter_role", UserRole.WAITER);
        modelAndView.addObject("auth_user", this.userService.getAuthenticatedUser());
        modelAndView.addObject("roles", UserRole.values());
        modelAndView.setViewName("order/waiter/all");
        return modelAndView;
    }

}

src/main/webapp/WEB-INF/views/order/manager/all.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html removeIntertagSpaces="true">
    <!DOCTYPE HTML>
    <html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex,nofollow">
        <meta name="title" content="Orders || Cafe Manager">
        <title>Orders || Cafe Manager</title>
        <link rel="shortcut icon" href="<c:url value="/resources/img/favicon.ico"/>" type="image/x-icon">
        <link rel="icon" href="<c:url value="/resources/img/favicon.ico"/>" type="image/x-icon">
        <link href="<c:url value="/resources/css/bootstrap.min.css"/>" rel="stylesheet">
        <link href="<c:url value="/resources/css/animate.css"/>" rel="stylesheet">
        <link href="<c:url value="/resources/css/style.min.css"/>" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    </head>
    <body>
    <jsp:include page="../../other/waiter_navbar.jsp"/>
    <div class="container-fluid">
        <section id="orderEntities">
            <div class="row manager-page">
                <c:set var="orders_length" value="${fn:length(orders)}"/>
                <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xl-10 col-xl-offset-1">
                    <div class="row section-name text-shadow">
                        <b>
                            <span class="color-brown">Orders</span>
                            <c:if test="${orders_length eq 0}">
                                <span class="color-red"> - The list is empty!</span>
                            </c:if>
                        </b>
                    </div>
                </div>
                <c:if test="${orders_length gt 0}">
                    <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xl-10 col-xl-offset-1 full-cart">
                        <table class="table">
                            <tr>
                                <th>Order Code</th>
                                <th>Status</th>
                                <th class="hidden-xs">Created Date</th>
                                <th>
                                    Actions
                                    <a href="<c:url value="/manager/order/delete_all"/>" title="Delete all orders">
                                        <button class="btn btn-danger" type="submit">Delete ALL</button>
                                    </a>
                                </th>
                            </tr>
                            <c:forEach items="${orders}" var="order">
                                <tr>
                                    <td>${order.orderCode}</td>
                                    <td>
                                        <c:choose>
                                            <c:when test="${order.status eq status_new}">
                                                <span class="color-green">${order.status}</span>
                                            </c:when>
                                            <c:otherwise>${order.status}</c:otherwise>
                                        </c:choose>
                                    </td>
                                    <td class="hidden-xs">${order.createdAt}</td>
                                    <td>
                                        <a href="<c:url value="/manager/order/view/${order.id}"/>"
                                           title="View ${order.orderCode} Order">
                                            <button class="btn btn-info" type="submit">View</button>
                                        </a>
                                        <a href="<c:url value="/manager/order/edit/${order.id}"/>"
                                           title="Edit ${order.orderCode} Order">
                                            <button class="btn btn-success" type="submit">Edit</button>
                                        </a>
                                        <a href="<c:url value="/manager/order/delete/${order.id}"/>"
                                           title="Delete ${order.orderCode} Order">
                                            <button class="btn btn-danger" type="submit">Delete</button>
                                        </a>
                                    </td>
                                </tr>
                            </c:forEach>
                        </table>
                    </div>
                </c:if>
            </div>
        </section>
    </div>
    <script src="<c:url value="/resources/js/jquery-1.11.1.min.js"/>"></script>
    <script src="<c:url value="/resources/js/jquery.appear.js"/>"></script>
    <script src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <script src="<c:url value="/resources/js/jquery.maskedinput.min.js"/>"></script>
    </body>
    </html>
</html>

src/main/webapp/WEB-INF/views/order/manager/one.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" trimDirectiveWhitespaces="true" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html removeIntertagSpaces="true">
    <!DOCTYPE HTML>
    <html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex,nofollow">
        <meta name="title" content="Order ${order.orderCode} || Cafe Manager">
        <title>Order ${order.orderCode} || Cafe Manager</title>
        <link rel="shortcut icon" href="<c:url value="/resources/img/favicon.ico"/>" type="image/x-icon">
        <link rel="icon" href="<c:url value="/resources/img/favicon.ico"/>" type="image/x-icon">
        <link href="<c:url value="/resources/css/bootstrap.min.css"/>" rel="stylesheet">
        <link href="<c:url value="/resources/css/animate.css"/>" rel="stylesheet">
        <link href="<c:url value="/resources/css/style.min.css"/>" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    </head>
    <body>
    <jsp:include page="../../other/manager_navbar.jsp"/>
    <div class="container-fluid">
        <section id="order">
            <div class="row admin-page">
                <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xl-10 col-xl-offset-1">
                    <div class="row section-name text-shadow">
                        <b><span class="color-brown">Order </span><span class="color-green">${order.orderCode}</span></b>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-10 col-lg-offset-1 col-xl-10 col-xl-offset-1 full-cart">
                    <table class="table">
                        <tr>
                            <th>Order Code:</th>
                            <td>${order.orderCode}</td>
                        </tr>
                        <tr>
                            <th>Status:</th>
                            <td>
                                <c:choose>
                                    <c:when test="${order.status eq status_new}">
                                        <span class="color-green"><b>${order.status}</b></span>
                                    </c:when>
                                    <c:otherwise>${order.status}</c:otherwise>
                                </c:choose>
                            </td>
                        </tr>
                        <tr>
                            <th>Creation Date:</th>
                            <td>${order.createdAt}</td>
                        </tr>
                        <tr>
                            <th>Waiter:</th>
                            <td>
                                <c:choose>
                                    <c:when test="${water ne null}">
                                        <c:choose>
                                            <c:when test="${water.role eq maanger_role}">
                                                <span class="color-red">${water.role}</span>
                                            </c:when>
                                            <c:when test="${water.role eq waiter_role}">
                                                <span class="color-green">${water.role}</span>
                                            </c:when>
                                            <c:otherwise>${water.role}</c:otherwise>
                                        </c:choose>
                                        <a href="<c:url value="/manager/user/view/${water.id}"/>">
                                                ${water.firstName}
                                        </a>
                                    </c:when>
                                    <c:otherwise>-</c:otherwise>
                                </c:choose>
                            </td>
                        </tr>
                        <tr>
                            <th>Details:</th>
                            <td>
                                <c:choose>
                                    <c:when test="${not empty order.description}">
                                        ${order.description}
                                    </c:when>
                                    <c:otherwise>-</c:otherwise>
                                </c:choose>
                            </td>
                        </tr>
                        <tr>
                            <th>Order Items:</th>
                            <td>
                                <c:choose>
                                    <c:when test="${fn:length(orderItems) gt 0}">
                                        <c:forEach items="${orderItems}" var="item">
                                            <a href="<c:url value="/product/${item.product.url}"/>"
                                               title="Move to product ${item.product.title}">
                                                    ${item.product.title}
                                            </a>, № ${item.product.id},
                                            <br>${item.stockCode} x ${item.product.price} грн
                                            <br>--------------<br>
                                        </c:forEach>
                                    </c:when>
                                    <c:otherwise>The List Of Items Empty!</c:otherwise>
                                </c:choose>
                            </td>
                        </tr>
                        <tr>
                            <th>Total Price/th>
                            <td><b>${order.paidTotal}</b> грн</td>
                        </tr>
                        <tr>
                            <th></th>
                            <td>
                                <a href="<c:url value="/manager/order/edit/${order.id}"/>"
                                   title="Edit ${order.number} Order ">
                                    <button class="btn btn-success" type="submit">Edit</button>
                                </a>
                                <a href="<c:url value="/manager/order/delete/${order.id}"/>"
                                   title="Delete ${order.number} Order">
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </a>
                                <a href="<c:url value="/manager/order/all"/>" title="Back to all Orders">
                                    <button class="btn btn-info" type="submit">Back</button>
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </section>
    </div>
    <script src="<c:url value="/resources/js/jquery-1.11.1.min.js"/>"></script>
    <script src="<c:url value="/resources/js/jquery.appear.js"/>"></script>
    <script src="<c:url value="/resources/js/bootstrap.min.js"/>"></script>
    <script src="<c:url value="/resources/js/jquery.maskedinput.min.js"/>"></script>
    </body>
    </html>
</html>